name: CI CD ANDROID

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Vérifier la version de EAS CLI
        run: npx eas --version

      # Condition pour la branche main uniquement
      - name: Build Android with EAS
        if: github.ref == 'refs/heads/main'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas build --platform android --non-interactive --profile test --wait

      - name: Get the build ID
        if: github.ref == 'refs/heads/main'
        run: |
          BUILD_ID=$(npx eas build:list --platform android --status finished --limit 1 --json | jq -r '.[0].id')
          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV

      - name: Download the latest Android build
        if: github.ref == 'refs/heads/main'
        run: |
          curl -o app-release.aab "https://api.expo.dev/v2/projects/${{ secrets.EAS_PROJECT_ID }}/builds/${BUILD_ID}/artifacts/app-release.aab"
          
      - name: Upload AAB to artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app-release.aab

      - name: Submit to Google Play
        if: github.ref == 'refs/heads/main'
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: npx eas submit --platform android --non-interactive --profile test --path app-release.aab --track internal
