# This is a basic workflow to help you get started with Actions

name: CI CD ANDROID

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

       # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '18'

     # Install dependencies
      - name: Install dependencies
        run: npm install

     # Install Expo CLI globally
      - name: Install Expo CLI and EAS CLI
        run: | 
          npm install -g expo-cli
          npm install -g eas-cli

      - name: Build Android with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --non-interactive --profile test
    
      - name: Download build artifact
        run: |
          eas build:download --platform android --path app-release.aab

      - name: Submit to Google Play
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: eas submit --platform android --non-interactive --profile test --path android/app/build/outputs/bundle/release/app-release.aab --track interna
